site_name: 葱喵Bot文档
site_url: https://docs.bot.ty0.icu
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  palette:
    primary: lime

extra:
  homepage: https://docs.bot.ty0.icu